python3-installer
python3-semantic-version
python3-flit_core
python3-flit
python3-pep517
python3-build
python3-setuptools_scm_git_archive
scikit-build
python2-setuptools-scm
python2-scandir
more-itertools
funcsigs
python2-attrs
python3-attrs
atomicwrites
iniconfig
entrypoints
python-toml
python3-more-itertools
python3-semantic-version
pyasn1
asn1crypto
wheel
python-jeepney
python3-setuptools_autover
nose
typing-extensions
incremental
mistune
hyperlink
constantly
zope.interface
pyserial
singledispatch
python3-parso
send2trash
python3-isort
python3-wrapt
python3-lazy-object-proxy
typing-extensions
mypy_extensions
python3-webencodings
html2text
pathlib2
python3-jedi
python3-astroid
py
pluggy
pytest
python3-pytest
python3-setuptools-rust
pytest-runner
python3-mccabe
cryptography
secretstorage
python-keyring
python3-uth
pyasn1-modules
python3-service-identity
python-m2r
python3-automat
python3-twisted
python3-pylint
mypy
asttokens
