perl-common-sense
perl-Cpanel-JSON-XS
perl-JSON
perl-http-tiny
perl-tk
perl-CPAN-Changes
perl-Params-Util
perl-Term-ReadLine-Gnu
perl-Log-Message
perl-Text-CSV
perl-Text-CSV_XS
perl-PAR-Dist
perl-Archive-Zip
perl-ExtUtils-Install
perl-Cstools
perl-Unicode-Map
perl-Unicode-String
perl-YAML-Tiny
perl-Exporter-Tiny
perl-List-MoreUtils-XS
perl-encode-locale
perl-Encode-EUCJPASCII
perl-Encode-ISO2022
perl-Devel-Symdump
perl-Devel-StackTrace
perl-Class-Data-Inheritable
perl-Sub-Uplevel
perl-Algorithm-Diff
perl-Capture-Tiny
perl-Try-Tiny
perl-data-dump
perl-Probe-Perl
perl-IPC-System-Simple
perl-IPC-Run3
perl-Tie-IxHash
perl-Pod-Parser
perl-Text-CharWidth
perl-Test-Harness
perl-Test-Pod
perl-Test-Requires
perl-Test-RequiresInternet
perl-Test-Warnings
perl-Test-NoWarnings
perl-IO-stringy
perl-Convert-BinHex
perl-TimeDate
perl-MIME-Types
perl-IO-Tty
perl-libintl
perl-Text-Glob
perl-Module-Build
perl-Unicode-Map8
perl-List-MoreUtils
perl-File-Remove
perl-Module-Install
perl-Encode-Detect
perl-Encode-HanExtra
perl-Encode-JISX0213
perl-MIME-Charset
perl-Unicode-LineBreak
perl-Exception-Class
perl-Text-Diff
perl-Test-Fatal
perl-Pod-Coverage
perl-Text-WrapI18N
perl-Test-Script
perl-Test-Simple
perl-Test-Pod-Coverage
perl-Test-utf8
perl-Test-Trap
perl-Test-Differences
perl-Test-Deep
perl-test-warn
perl-Test-Exception
perl-Test-Most
perl-MailTools
perl-MIME-tools
perl-IO-Stty
perl-Expect
perl-File-Finder
perl-Log-Message-Simple
perl-Module-Implementation
perl-Package-Stash-XS
perl-Sub-Install
perl-Data-OptList
perl-Sub-Exporter
perl-Dist-CheckConflicts
perl-Package-Stash
perl-Test-Spec
perl-Module-Runtime-Conflicts
